name: "ESLint+"
author: "Andrew Ewing <drew@collaboratory.io>"
description: "Check source code with ESLint."
inputs:
  token:
    description: "github security token"
    required: true
  directory:
    description: "directory (relative to node_modules)"
    required: true
  eslintconfig:
    description: "relative path to eslintconfig file eg. .eslintrc"
    required: true
  eslintignore:
    description: "relative path to .eslintignore"
    required: true
  extensions:
    description: "comma separated list of file extensions"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "check-circle"
  color: "blue"
